# Generated by Django 4.0.4 on 2022-04-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name_plural': 'time table'},
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='subject',
            new_name='course',
        ),
    ]
