# Generated by Django 4.0.4 on 2022-04-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
    ]
