# Generated by Django 4.0.4 on 2022-04-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_timetable_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
        migrations.AddField(
            model_name='timetable',
            name='batch',
            field=models.ManyToManyField(to='base.batch'),
        ),
    ]
