# Generated by Django 4.0.4 on 2022-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
