# Generated by Django 4.0.4 on 2022-05-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('base', '0010_notifications_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
