# Generated by Django 4.0.4 on 2022-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_notifications_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
