# Generated by Django 4.0.4 on 2022-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_notifications_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='batch',
        ),
        migrations.AddField(
            model_name='notifications',
            name='batch',
            field=models.ManyToManyField(to='base.batch'),
        ),
    ]
