# Generated by Django 4.0.4 on 2022-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_notifications_batch_notifications_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
    ]
