# Generated by Django 4.0.4 on 2022-05-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('base', '0014_notifications_isseen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'notifications'},
        ),
    ]
